spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://34.65.164.242:3306/rumpy?serverTimezone=UTC
    username: root
    password: pCztd0p9hnbHBpdK
server:
  port: 8081