spring:
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: gc

file:
  storage:
    location: fileStorage

paystack:
  secret_key: sk_test_18d0ed8d86d0a4a48bad31d655442050e01920bc








